export const RouteNames = {
  HOME: 'home',
  LOGIN: 'login',
  SIGNUP: 'signup',
  VERIFY_EMAIL_NOTICE: 'verify-email-notice',
  VERIFY_EMAIL: 'verify-email',
  ONBOARDING_CREATE_CLINIC: 'onboarding-create-clinic',
  SELECT_CLINIC: 'select-clinic',
  PATIENT_LIST: 'patient-list',
  PATIENT_DETAIL: 'patient-detail',
  AUDIT_LOG_LIST: 'audit-log-list',
  AUDIT_LOG_DETAIL: 'audit-log-detail',
  ENCOUNTER_NEW: 'encounter-new',
  ENCOUNTER_DETAIL: 'encounter-detail',
  CLINIC: 'clinic',
  CLINIC_PROFILE: 'clinic-profile',
  CLINIC_SETTINGS: 'clinic-settings',
  CLINIC_MEDICINES: 'clinic-medicines',
  CLINIC_CONSUMABLES: 'clinic-consumables',
  CLINIC_LAB_SERVICES: 'clinic-lab-services',
  CLINIC_TEMPLATES: 'clinic-templates',
  MEDICINE_LIST: 'medicine-list',
  APPOINTMENT_LIST: 'appointment-list',
  SCHEDULE: 'schedule',
  QUEUE: 'queue',
  TEAM: 'team',
  ROLES: 'roles',
  MESSAGES: 'messages',
  ACCOUNT: 'account',
  COMPONENTS: 'components',
  QUEUE_DISPLAY: 'queue-display',
  BILLING: 'billing',
  SUBSCRIPTION: 'subscription',
  PAYMENT_SUCCESS: 'payment-success',
  PAYMENT_CANCELLED: 'payment-cancelled',
  TEMPLATE_EDITOR: 'template-editor',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_PASSWORD: 'reset-password',
  PREGNANCY_CREATE: 'pregnancy-create',
  PREGNANCY_DETAIL: 'pregnancy-detail',
  CLINIC_SERVICES: 'clinic-services',
  PRENATAL_VISIT_CREATE: 'prenatal-visit-create',
  PRENATAL_VISIT_DETAIL: 'prenatal-visit-detail',
  ODONTOGRAM_PLAYGROUND: 'odontogram-playground',
} as const

export type RouteName = (typeof RouteNames)[keyof typeof RouteNames]
