export { default as Tabs } from "./Tabs.vue"
export { type TabsSize } from "./tabs"
export { default as TabsContent } from "./TabsContent.vue"
export { default as TabsList } from "./TabsList.vue"
export { default as TabsTrigger } from "./TabsTrigger.vue"
